[package]
name = "init"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"  # Optimize for size

[[bin]]
name = "init"
path = "src/main.rs"
