[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-T/Users/nattaponra/Desktop/mellos/kernel/userspace/mellobox/linker.ld",
    "-C", "relocation-model=static",
]
